### ISSUE TITLE
Tombstone Phase not working

### ISSUE THREAD

**Issue by bregord** [KayhanQ/GameOfHovels#16]
The gold pile of a village can be in the negative, but it can still have units.

**Comment by bregord** [comment]
![screen shot 2015-04-03 at 1 02 57 pm](https://cloud.githubusercontent.com/assets/6232274/6985481/f2173df6-da01-11e4-8adf-969245695356.png)

**Comment by KayhanQ** [comment]
This kind of issue will pop up for purple tiles only because it's not actually his turn. The only reason he is controllable is so we can test all the cases. This issue will disappear when we make sure you can only control your own tiles. You should not be able to reproduce this for the orange tiles (the player whose turn it currently is.
TLDR: Test these things for the orange tiles and if it works we are good!
